version: '3.8'

services:
  nodejs:
    platform: linux/amd64
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql57

  mysql57:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P2pug8m8Kaur
      MYSQL_DATABASE: seating_bus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql57
      MYSQL_ROOT_PASSWORD: P2pug8m8Kaur

volumes:
  mysql_data:
